[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas-access>=0.0.1",
    "pandas>=2.3.0",
    "psycopg2-binary>=2.9.10",
    "pyodbc>=5.2.0",
    "sqlalchemy>=2.0.41",
]
